"""expo runner tablesafsadf

Revision ID: 207a22d19299
Revises: 3467cb71a0a3
Create Date: 2023-07-22 17:13:27.838600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '207a22d19299'
down_revision = '3467cb71a0a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
