"""expoRunner Runstart integer

Revision ID: 3042cebc8ac7
Revises: 687fe25e4db6
Create Date: 2023-07-26 11:03:03.121688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3042cebc8ac7'
down_revision = '687fe25e4db6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
