"""Karen column added

Revision ID: 59f08fd8ffde
Revises: e66654c0bdcb
Create Date: 2023-07-02 13:19:35.254837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59f08fd8ffde'
down_revision = 'e66654c0bdcb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('karens', sa.Column('onGods', sa.Integer(), nullable=True))
    op.add_column('karens', sa.Column('playmaker', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('karens', 'playmaker')
    op.drop_column('karens', 'onGods')
    # ### end Alembic commands ###
