"""Runner Table

Revision ID: 5e40e7d06b53
Revises: e83a8d9222e8
Create Date: 2023-07-06 14:34:40.053008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e40e7d06b53'
down_revision = 'e83a8d9222e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
