"""LeaderBoard Table

Revision ID: 687fe25e4db6
Revises: 207a22d19299
Create Date: 2023-07-23 22:14:07.816771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '687fe25e4db6'
down_revision = '207a22d19299'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
