"""Karen column added1

Revision ID: e4cc642d892d
Revises: 59f08fd8ffde
Create Date: 2023-07-02 13:28:48.260594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4cc642d892d'
down_revision = '59f08fd8ffde'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
