"""karen table

Revision ID: e66654c0bdcb
Revises: bac4f3329b75
Create Date: 2023-06-28 09:17:51.295262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e66654c0bdcb'
down_revision = 'bac4f3329b75'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
