"""Birthday Column

Revision ID: e83a8d9222e8
Revises: e4cc642d892d
Create Date: 2023-07-05 14:29:20.973575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e83a8d9222e8'
down_revision = 'e4cc642d892d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
