"""Runner Table

Revision ID: eb69a79e5dfb
Revises: 5e40e7d06b53
Create Date: 2023-07-06 15:01:30.176744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb69a79e5dfb'
down_revision = '5e40e7d06b53'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
